data:
  class_path: datasets.PedestrianDataModule
  init_args:
    data_dir: "../../../dataset/worldtrack/mmp_industry_safety_0"
    batch_size: 2
    num_workers: 4
model:
  resolution: [64, 4, 64]      # Y,Z,X  (BEV voxel grid)
  bounds: [0, 256, 0, 256, 0, 60]  # xmin,xmax,ymin,ymax,zmin,zmax in worldgrid units
  depth: [32, 250, 4000]
  num_cameras: 4
  use_temporal_cache: False
trainer:
  max_epochs: 30
